#![cfg(test)]

// No mocks: the verifier deployed here runs the actual compiled
// verifier.wasm, and "valid proof" tests use genuinely valid Groth16
// proofs generated with mainline ark-groth16/ark-bls12-381 (no Circom
// needed for this — see verifier::test for why a tiny in-Rust circuit is
// enough, and for a golden test against Stellar's own published proof).
// Placeholder circuits (NInputCircuit) stand in for transfer/withdraw for
// the bulk of the test suite; real_circom_* golden tests at the bottom use
// actual proofs generated by snarkjs from the compiled transfer.circom /
// withdraw.circom, validating the full circuit→contract round-trip.

extern crate std;

use crate::commitment::{self, Point};
use crate::verifier::{verifier_contract, Proof, VerificationKey};
use crate::{Piilo, PiiloClient, PiiloError};
use ark_bls12_381::{Bls12_381, Fq, Fq2, Fr as ArkFr};
use ark_ff::PrimeField;
use ark_groth16::{Groth16, Proof as ArkProof, ProvingKey};
use ark_relations::gr1cs::{ConstraintSynthesizer, ConstraintSystemRef, SynthesisError, Variable};
use ark_serialize::CanonicalSerialize;
use ark_std::rand::{rngs::StdRng, SeedableRng};
use core::str::FromStr;
use soroban_sdk::{
    crypto::bls12_381::{Fr, G1Affine, G2Affine, G1_SERIALIZED_SIZE, G2_SERIALIZED_SIZE},
    testutils::Address as _,
    token, Address, Bytes, BytesN, Env,
};

/// Ties N public inputs to a witness via one R1CS constraint (w*1 =
/// inputs[0]) — same minimal-circuit pattern the verifier's own tests use,
/// generic over the public input count so it can stand in for either the
/// transfer (N=6) or withdraw (N=3) shape.
#[derive(Clone)]
struct NInputCircuit<const N: usize> {
    inputs: [ArkFr; N],
}

impl<const N: usize> ConstraintSynthesizer<ArkFr> for NInputCircuit<N> {
    fn generate_constraints(self, cs: ConstraintSystemRef<ArkFr>) -> Result<(), SynthesisError> {
        let first = cs.new_input_variable(|| Ok(self.inputs[0]))?;
        for i in 1..N {
            let _ = cs.new_input_variable(|| Ok(self.inputs[i]))?;
        }
        let witness = cs.new_witness_variable(|| Ok(self.inputs[0]))?;
        cs.enforce_r1cs_constraint(|| witness.into(), || Variable::One.into(), || first.into())?;
        Ok(())
    }
}

fn g1_to_sdk(env: &Env, p: ark_bls12_381::G1Affine) -> G1Affine {
    let mut buf = [0u8; G1_SERIALIZED_SIZE];
    p.serialize_uncompressed(&mut buf[..]).unwrap();
    G1Affine::from_array(env, &buf)
}

fn g2_to_sdk(env: &Env, p: ark_bls12_381::G2Affine) -> G2Affine {
    let mut buf = [0u8; G2_SERIALIZED_SIZE];
    p.serialize_uncompressed(&mut buf[..]).unwrap();
    G2Affine::from_array(env, &buf)
}

fn vk_to_sdk(env: &Env, vk: &ark_groth16::VerifyingKey<Bls12_381>) -> VerificationKey {
    let mut ic = soroban_sdk::Vec::new(env);
    for p in vk.gamma_abc_g1.iter() {
        ic.push_back(g1_to_sdk(env, *p).into());
    }
    VerificationKey {
        alpha: g1_to_sdk(env, vk.alpha_g1).into(),
        beta: g2_to_sdk(env, vk.beta_g2).into(),
        gamma: g2_to_sdk(env, vk.gamma_g2).into(),
        delta: g2_to_sdk(env, vk.delta_g2).into(),
        ic,
    }
}

fn proof_to_sdk(env: &Env, proof: &ArkProof<Bls12_381>) -> Proof {
    Proof {
        a: g1_to_sdk(env, proof.a).into(),
        b: g2_to_sdk(env, proof.b).into(),
        c: g1_to_sdk(env, proof.c).into(),
    }
}

struct Circuit<const N: usize> {
    pk: ProvingKey<Bls12_381>,
}

fn setup_circuit<const N: usize>(rng: &mut StdRng) -> Circuit<N> {
    let dummy = NInputCircuit::<N> { inputs: [ArkFr::from(1u64); N] };
    let pk = Groth16::<Bls12_381>::generate_random_parameters_with_reduction(dummy, rng).expect("groth16 setup");
    Circuit { pk }
}

fn prove<const N: usize>(env: &Env, circuit: &Circuit<N>, rng: &mut StdRng, inputs: [ArkFr; N]) -> Proof {
    let proof = Groth16::<Bls12_381>::create_random_proof_with_reduction(NInputCircuit { inputs }, &circuit.pk, rng)
        .expect("groth16 prove");
    proof_to_sdk(env, &proof)
}

fn rng() -> StdRng {
    StdRng::seed_from_u64(42)
}

/// Mirrors lib.rs's points_to_inputs: each commitment coordinate already
/// is an Fr element (the whole point of JubJub), reduced the same way the
/// host reduces U256 -> Fr — so this is the exact, final encoding, not a
/// placeholder.
fn point_to_ark_frs(p: &Point) -> [ArkFr; 2] {
    let x = ArkFr::from_be_bytes_mod_order(&p.x.to_array());
    let y = ArkFr::from_be_bytes_mod_order(&p.y.to_array());
    [x, y]
}

fn amount_to_ark_fr(amount: i128) -> ArkFr {
    let mut buf = [0u8; 32];
    buf[16..32].copy_from_slice(&(amount as u128).to_be_bytes());
    ArkFr::from_be_bytes_mod_order(&buf)
}

/// A genuine point on the JubJub curve (y = 3, x solved from the curve
/// equation and verified via Tonelli-Shanks modular sqrt independently in
/// Python — see commitment.rs's test module for the same point and the
/// derivation). Scalar multiples of a genuine on-curve point are also
/// on-curve, so this gives an unlimited supply of valid, distinct points —
/// unlike an arbitrary off-curve (x, y) dummy pair, which would make G/H
/// (and everything committed with them) not actually live on the curve
/// the commitment scheme is supposed to use.
fn base_point(env: &Env) -> Point {
    let x = BytesN::from_array(
        env,
        &[
            0x71, 0xd5, 0x66, 0x03, 0x4f, 0x97, 0x98, 0x31, 0x17, 0x11, 0xae, 0x45, 0xd3, 0x6b,
            0x76, 0xbb, 0x0c, 0xa1, 0x09, 0xd6, 0x62, 0xff, 0x23, 0xf9, 0xd5, 0xca, 0x97, 0x9f,
            0xee, 0x80, 0x18, 0x97,
        ],
    );
    let y = fr(env, 3).to_bytes();
    Point { x, y }
}

fn test_point(env: &Env, seed: u64) -> Point {
    commitment::scalar_mul(env, &base_point(env), &fr(env, seed))
}

fn fr(env: &Env, v: u64) -> Fr {
    let mut buf = [0u8; 32];
    buf[24..32].copy_from_slice(&v.to_be_bytes());
    Fr::from_bytes(BytesN::from_array(env, &buf))
}

fn blinding(env: &Env, v: u64) -> BytesN<32> {
    let mut buf = [0u8; 32];
    buf[24..32].copy_from_slice(&v.to_be_bytes());
    BytesN::from_array(env, &buf)
}

struct Setup {
    env: Env,
    piilo_id: Address,
    token_id: Address,
    g: Point,
    h: Point,
    transfer_circuit: Circuit<6>,
    withdraw_circuit: Circuit<3>,
}

fn setup() -> Setup {
    let env = Env::default();
    // soroban-sdk 25 enforces mainnet per-invocation resource limits by
    // default. Each individual deposit/transfer/withdraw call fits within
    // them on its own (confirmed: single-call tests pass without this) —
    // but tests here run several calls back-to-back against one Env with
    // no transaction boundary to reset the budget at, which isn't
    // representative of real usage. See commitment.rs's test module for
    // the same note; windowed precomputed tables for G/H would be the
    // real optimization before mainnet, not needed for this MVP.
    env.cost_estimate().disable_resource_limits();
    env.cost_estimate().budget().reset_unlimited();
    env.mock_all_auths();
    let mut r = rng();

    let admin = Address::generate(&env);
    let sac = env.register_stellar_asset_contract_v2(admin.clone());
    let token_id = sac.address();

    let verifier_id = env.register(verifier_contract::WASM, ());

    let transfer_circuit = setup_circuit::<6>(&mut r);
    let withdraw_circuit = setup_circuit::<3>(&mut r);
    let transfer_vk = vk_to_sdk(&env, &transfer_circuit.pk.vk);
    let withdraw_vk = vk_to_sdk(&env, &withdraw_circuit.pk.vk);

    let g = test_point(&env, 100);
    let h = test_point(&env, 200);

    let piilo_id = env.register(
        Piilo,
        (g.clone(), h.clone(), verifier_id, transfer_vk, withdraw_vk, token_id.clone()),
    );

    Setup {
        env,
        piilo_id,
        token_id,
        g,
        h,
        transfer_circuit,
        withdraw_circuit,
    }
}

fn fund(env: &Env, token_id: &Address, user: &Address, amount: i128) {
    token::StellarAssetClient::new(env, token_id).mint(user, &amount);
}

fn expected_commitment(env: &Env, g: &Point, h: &Point, amount: i128, blind_seed: u64) -> Point {
    let value_fr = commitment::fr_from_i128(env, amount);
    let blinding_fr = Fr::from_bytes(blinding(env, blind_seed));
    commitment::commit(env, &value_fr, &blinding_fr, g, h)
}

/// Builds a genuinely valid transfer proof for the exact (balance, c_a,
/// c_new) the contract will check against.
fn transfer_proof(s: &Setup, balance: &Point, c_a: &Point, c_new: &Point) -> Proof {
    let [b0, b1] = point_to_ark_frs(balance);
    let [a0, a1] = point_to_ark_frs(c_a);
    let [n0, n1] = point_to_ark_frs(c_new);
    prove(&s.env, &s.transfer_circuit, &mut rng(), [b0, b1, a0, a1, n0, n1])
}

fn withdraw_proof(s: &Setup, balance: &Point, amount: i128) -> Proof {
    let [b0, b1] = point_to_ark_frs(balance);
    prove(&s.env, &s.withdraw_circuit, &mut rng(), [b0, b1, amount_to_ark_fr(amount)])
}

fn dummy_proof(env: &Env) -> Proof {
    let zero = G1Affine::from_array(env, &[0u8; G1_SERIALIZED_SIZE]);
    let zero2 = G2Affine::from_array(env, &[0u8; G2_SERIALIZED_SIZE]);
    Proof { a: zero.clone().into(), b: zero2.into(), c: zero.into() }
}

#[test]
fn deposit_creates_account_and_funds_vault() {
    let s = setup();
    let client = PiiloClient::new(&s.env, &s.piilo_id);
    let token_client = token::Client::new(&s.env, &s.token_id);
    let user = Address::generate(&s.env);
    fund(&s.env, &s.token_id, &user, 1_000);

    client.deposit(&user, &500, &blinding(&s.env, 7));

    assert_eq!(token_client.balance(&user), 500);
    assert_eq!(token_client.balance(&s.piilo_id), 500);
    assert_eq!(client.get_vault_balance(), 500);

    let account = client.get_account(&user).unwrap();
    let expected = expected_commitment(&s.env, &s.g, &s.h, 500, 7);
    assert_eq!(account.balance_commitment, expected);
    assert!(!account.has_pending);
    assert_eq!(account.nonce, 0);
}

#[test]
fn second_deposit_merges_homomorphically() {
    let s = setup();
    let client = PiiloClient::new(&s.env, &s.piilo_id);
    let user = Address::generate(&s.env);
    fund(&s.env, &s.token_id, &user, 1_000);

    client.deposit(&user, &300, &blinding(&s.env, 1));
    client.deposit(&user, &200, &blinding(&s.env, 2));

    let account = client.get_account(&user).unwrap();

    let c1 = expected_commitment(&s.env, &s.g, &s.h, 300, 1);
    let c2 = expected_commitment(&s.env, &s.g, &s.h, 200, 2);
    let expected = commitment::add(&s.env, &c1, &c2);

    assert_eq!(account.balance_commitment, expected);
    assert_eq!(client.get_vault_balance(), 500);
}

#[test]
fn deposit_rejects_non_positive_amount() {
    let s = setup();
    let client = PiiloClient::new(&s.env, &s.piilo_id);
    let user = Address::generate(&s.env);
    fund(&s.env, &s.token_id, &user, 1_000);

    let result = client.try_deposit(&user, &0, &blinding(&s.env, 1));
    assert_eq!(result, Err(Ok(PiiloError::InvalidAmount)));
}

#[test]
fn transfer_with_valid_proof_updates_sender_and_recipient() {
    let s = setup();
    let client = PiiloClient::new(&s.env, &s.piilo_id);
    let alice = Address::generate(&s.env);
    let bob = Address::generate(&s.env);
    fund(&s.env, &s.token_id, &alice, 1_000);
    client.deposit(&alice, &100, &blinding(&s.env, 1));

    let balance = client.get_account(&alice).unwrap().balance_commitment;
    let c_a = test_point(&s.env, 300);
    let c_new = test_point(&s.env, 400);
    let proof = transfer_proof(&s, &balance, &c_a, &c_new);
    let note = Bytes::from_array(&s.env, &[1u8; 4]);

    client.transfer(&alice, &bob, &c_a, &c_new, &proof, &note);

    let alice_account = client.get_account(&alice).unwrap();
    assert_eq!(alice_account.balance_commitment, c_new);
    assert_eq!(alice_account.nonce, 1);

    let bob_account = client.get_account(&bob).unwrap();
    assert!(bob_account.has_pending);
    assert_eq!(bob_account.pending_commitment, c_a);
}

#[test]
fn transfer_accumulates_pending_from_multiple_senders() {
    let s = setup();
    let client = PiiloClient::new(&s.env, &s.piilo_id);
    let alice = Address::generate(&s.env);
    let carol = Address::generate(&s.env);
    let bob = Address::generate(&s.env);
    fund(&s.env, &s.token_id, &alice, 1_000);
    fund(&s.env, &s.token_id, &carol, 1_000);

    client.deposit(&alice, &100, &blinding(&s.env, 1));
    client.deposit(&carol, &100, &blinding(&s.env, 2));

    let alice_balance = client.get_account(&alice).unwrap().balance_commitment;
    let carol_balance = client.get_account(&carol).unwrap().balance_commitment;
    let c_a1 = test_point(&s.env, 11);
    let c_a2 = test_point(&s.env, 22);
    let c_new1 = test_point(&s.env, 91);
    let c_new2 = test_point(&s.env, 92);

    let proof1 = transfer_proof(&s, &alice_balance, &c_a1, &c_new1);
    let proof2 = transfer_proof(&s, &carol_balance, &c_a2, &c_new2);
    let note = Bytes::from_array(&s.env, &[0u8; 4]);

    client.transfer(&alice, &bob, &c_a1, &c_new1, &proof1, &note);
    client.transfer(&carol, &bob, &c_a2, &c_new2, &proof2, &note);

    let bob_account = client.get_account(&bob).unwrap();
    let expected = commitment::add(&s.env, &c_a1, &c_a2);
    assert_eq!(bob_account.pending_commitment, expected);
}

#[test]
fn transfer_with_proof_for_wrong_statement_is_rejected() {
    let s = setup();
    let client = PiiloClient::new(&s.env, &s.piilo_id);
    let alice = Address::generate(&s.env);
    let bob = Address::generate(&s.env);
    fund(&s.env, &s.token_id, &alice, 1_000);
    client.deposit(&alice, &100, &blinding(&s.env, 1));

    let balance = client.get_account(&alice).unwrap().balance_commitment;
    let c_a = test_point(&s.env, 1);
    let c_new = test_point(&s.env, 2);
    // Proof is genuinely valid, but for a DIFFERENT c_new than what's
    // actually submitted — real cryptographic rejection, not a hardcoded
    // false.
    let wrong_c_new = test_point(&s.env, 999);
    let proof = transfer_proof(&s, &balance, &c_a, &wrong_c_new);
    let note = Bytes::from_array(&s.env, &[0u8; 4]);

    let result = client.try_transfer(&alice, &bob, &c_a, &c_new, &proof, &note);
    assert_eq!(result, Err(Ok(PiiloError::InvalidProof)));
}

#[test]
fn transfer_without_existing_account_fails() {
    let s = setup();
    let client = PiiloClient::new(&s.env, &s.piilo_id);
    let alice = Address::generate(&s.env);
    let bob = Address::generate(&s.env);

    // Fails before proof verification is even reached, so any proof does.
    let note = Bytes::from_array(&s.env, &[0u8; 4]);
    let result = client.try_transfer(
        &alice,
        &bob,
        &test_point(&s.env, 1),
        &test_point(&s.env, 2),
        &dummy_proof(&s.env),
        &note,
    );
    assert_eq!(result, Err(Ok(PiiloError::NotInitialized)));
}

#[test]
fn settle_pending_merges_and_clears() {
    let s = setup();
    let client = PiiloClient::new(&s.env, &s.piilo_id);
    let alice = Address::generate(&s.env);
    let bob = Address::generate(&s.env);
    fund(&s.env, &s.token_id, &alice, 1_000);
    client.deposit(&alice, &100, &blinding(&s.env, 1));

    let balance = client.get_account(&alice).unwrap().balance_commitment;
    let c_a = test_point(&s.env, 300);
    let c_new = test_point(&s.env, 400);
    let proof = transfer_proof(&s, &balance, &c_a, &c_new);
    let note = Bytes::from_array(&s.env, &[0u8; 4]);
    client.transfer(&alice, &bob, &c_a, &c_new, &proof, &note);

    client.settle_pending(&bob);

    let bob_account = client.get_account(&bob).unwrap();
    assert!(!bob_account.has_pending);
    assert_eq!(bob_account.pending_commitment, commitment::identity(&s.env));
    assert_eq!(bob_account.balance_commitment, c_a);
}

#[test]
fn settle_pending_without_pending_fails() {
    let s = setup();
    let client = PiiloClient::new(&s.env, &s.piilo_id);
    let alice = Address::generate(&s.env);
    fund(&s.env, &s.token_id, &alice, 1_000);
    client.deposit(&alice, &100, &blinding(&s.env, 1));

    let result = client.try_settle_pending(&alice);
    assert_eq!(result, Err(Ok(PiiloError::NoPendingBalance)));
}

#[test]
fn withdraw_pays_out_and_resets_balance() {
    let s = setup();
    let client = PiiloClient::new(&s.env, &s.piilo_id);
    let token_client = token::Client::new(&s.env, &s.token_id);
    let alice = Address::generate(&s.env);
    fund(&s.env, &s.token_id, &alice, 1_000);
    client.deposit(&alice, &400, &blinding(&s.env, 1));

    let balance = client.get_account(&alice).unwrap().balance_commitment;
    let proof = withdraw_proof(&s, &balance, 400);
    client.withdraw(&alice, &400, &proof);

    assert_eq!(token_client.balance(&alice), 1_000);
    assert_eq!(client.get_vault_balance(), 0);

    let account = client.get_account(&alice).unwrap();
    assert_eq!(account.balance_commitment, commitment::identity(&s.env));
}

#[test]
fn withdraw_more_than_vault_fails() {
    let s = setup();
    let client = PiiloClient::new(&s.env, &s.piilo_id);
    let alice = Address::generate(&s.env);
    fund(&s.env, &s.token_id, &alice, 1_000);
    client.deposit(&alice, &100, &blinding(&s.env, 1));

    // Fails the vault check before verification, so any proof does.
    let result = client.try_withdraw(&alice, &200, &dummy_proof(&s.env));
    assert_eq!(result, Err(Ok(PiiloError::InsufficientVault)));
}

#[test]
fn withdraw_with_proof_for_wrong_amount_is_rejected() {
    let s = setup();
    let client = PiiloClient::new(&s.env, &s.piilo_id);
    let alice = Address::generate(&s.env);
    fund(&s.env, &s.token_id, &alice, 1_000);
    client.deposit(&alice, &100, &blinding(&s.env, 1));

    let balance = client.get_account(&alice).unwrap().balance_commitment;
    // Genuinely valid proof, but for withdrawing 50 — submitted against a
    // withdraw(100) call instead.
    let proof = withdraw_proof(&s, &balance, 50);
    let result = client.try_withdraw(&alice, &100, &proof);
    assert_eq!(result, Err(Ok(PiiloError::InvalidProof)));
}

/// Measures whether a *single* deposit (one commit() = two scalar_muls +
/// one add, all real fr_* host calls) fits within real mainnet
/// per-invocation resource limits — as opposed to the rest of this file's
/// tests, which run several calls against one Env with limits disabled
/// (see setup()'s comment for why that's a test-harness artifact, not a
/// per-call concern). This is the number that actually matters for "can
/// this be deployed."
#[test]
fn single_deposit_fits_real_mainnet_resource_limits() {
    let env = Env::default(); // mainnet limits enforced by default, budget NOT reset unlimited
    env.mock_all_auths();

    let admin = Address::generate(&env);
    let sac = env.register_stellar_asset_contract_v2(admin.clone());
    let token_id = sac.address();
    let verifier_id = env.register(verifier_contract::WASM, ());
    let mut r = rng();
    let transfer_vk = vk_to_sdk(&env, &setup_circuit::<6>(&mut r).pk.vk);
    let withdraw_vk = vk_to_sdk(&env, &setup_circuit::<3>(&mut r).pk.vk);
    let g = test_point(&env, 100);
    let h = test_point(&env, 200);
    let piilo_id = env.register(
        Piilo,
        (g, h, verifier_id, transfer_vk, withdraw_vk, token_id.clone()),
    );

    let client = PiiloClient::new(&env, &piilo_id);
    let user = Address::generate(&env);
    fund(&env, &token_id, &user, 1_000);

    client.deposit(&user, &500, &blinding(&env, 7));

    std::println!("{}", env.cost_estimate().budget());
}

/// Measures transfer()'s standalone real cost (1 add() + cross-contract
/// verify with 6 public inputs — no scalar_mul, unlike deposit). The
/// account needs a real prior deposit() to exist, which would itself eat
/// real budget if left enabled — so resource limits are disabled after
/// that setup deposit to isolate transfer()'s own cost cleanly. This is a
/// measurement, not a strict pass/fail gate (see the deposit-only test
/// above for that); see CLAUDE.md for the resulting numbers and what they
/// mean for real deployment.
#[test]
fn transfer_real_cost_measurement() {
    let env = Env::default();
    env.mock_all_auths();

    let admin = Address::generate(&env);
    let sac = env.register_stellar_asset_contract_v2(admin.clone());
    let token_id = sac.address();
    let verifier_id = env.register(verifier_contract::WASM, ());
    let mut r = rng();
    let transfer_circuit = setup_circuit::<6>(&mut r);
    let withdraw_circuit = setup_circuit::<3>(&mut r);
    let transfer_vk = vk_to_sdk(&env, &transfer_circuit.pk.vk);
    let withdraw_vk = vk_to_sdk(&env, &withdraw_circuit.pk.vk);
    let g = test_point(&env, 100);
    let h = test_point(&env, 200);
    let piilo_id = env.register(
        Piilo,
        (g, h, verifier_id, transfer_vk, withdraw_vk, token_id.clone()),
    );

    let client = PiiloClient::new(&env, &piilo_id);
    let alice = Address::generate(&env);
    let bob = Address::generate(&env);
    fund(&env, &token_id, &alice, 1_000);

    // deposit needs its own budget check (done separately); reset before
    // timing transfer specifically, matching how each would be a separate
    // transaction on a real network.
    client.deposit(&alice, &100, &blinding(&env, 1));
    // deposit() alone uses ~75% of the budget (measured separately); reset
    // to unlimited so transfer()'s own cost can be measured without
    // panicking on the ceiling deposit already ate into.
    env.cost_estimate().budget().reset_unlimited();

    let balance = client.get_account(&alice).unwrap().balance_commitment;
    let c_a = test_point(&env, 300);
    let c_new = test_point(&env, 400);
    let s = Setup {
        env: env.clone(),
        piilo_id: piilo_id.clone(),
        token_id: token_id.clone(),
        g: test_point(&env, 100),
        h: test_point(&env, 200),
        transfer_circuit,
        withdraw_circuit,
    };
    let proof = transfer_proof(&s, &balance, &c_a, &c_new);
    let note = Bytes::from_array(&env, &[1u8; 4]);

    client.transfer(&alice, &bob, &c_a, &c_new, &proof, &note);

    std::println!("{}", env.cost_estimate().budget());
}

#[test]
fn deposit_requires_user_auth() {
    let s = setup();
    let client = PiiloClient::new(&s.env, &s.piilo_id);
    let alice = Address::generate(&s.env);
    fund(&s.env, &s.token_id, &alice, 1_000);

    // setup() called mock_all_auths(); clear it to actually exercise
    // require_auth() enforcement instead of bypassing it.
    s.env.set_auths(&[]);
    let result = client.try_deposit(&alice, &100, &blinding(&s.env, 1));
    assert!(result.is_err());
}

// ── Golden tests: real Circom circuits ───────────────────────────────────────
//
// These use actual snarkjs-generated proofs from the compiled transfer.circom
// and withdraw.circom (circuits/build/transfer_proof.json, withdraw_proof.json),
// verifying the full circuit→contract round-trip with the real soundness relation
// (B >= A >= 0, commitment openings, etc.) rather than the placeholder NInputCircuit.
//
// VK and proof coordinates are hardcoded from circuits/build/{transfer,withdraw}_vk.json
// and circuits/build/{transfer,withdraw}_proof.json — same pattern as the verifier
// test's `matches_stellars_own_published_proof`. Inputs:
//   B=500, r_B=111, A=200, r_A=222, r_new=333
//   C_B = commit(500, 111, G, H)   [from input_transfer.json, verified by snarkjs]
//   C_A = commit(200, 222, G, H)
//   C_new = commit(300, 333, G, H)

fn g1_from_coords_snarkjs(env: &Env, x: &str, y: &str) -> G1Affine {
    let p = ark_bls12_381::G1Affine::new(Fq::from_str(x).unwrap(), Fq::from_str(y).unwrap());
    let mut buf = [0u8; G1_SERIALIZED_SIZE];
    p.serialize_uncompressed(&mut buf[..]).unwrap();
    G1Affine::from_array(env, &buf)
}

fn g2_from_coords_snarkjs(env: &Env, x_c0: &str, x_c1: &str, y_c0: &str, y_c1: &str) -> G2Affine {
    let x = Fq2::new(Fq::from_str(x_c0).unwrap(), Fq::from_str(x_c1).unwrap());
    let y = Fq2::new(Fq::from_str(y_c0).unwrap(), Fq::from_str(y_c1).unwrap());
    let p = ark_bls12_381::G2Affine::new(x, y);
    let mut buf = [0u8; G2_SERIALIZED_SIZE];
    p.serialize_uncompressed(&mut buf[..]).unwrap();
    G2Affine::from_array(env, &buf)
}

/// Piilo's actual generator G from jubjub.circom: PiiloGeneratorG().
fn circuit_g(env: &Env) -> Point {
    Point {
        x: BytesN::from_array(env, &[
            0x72, 0xfd, 0x4d, 0xce, 0x19, 0x9f, 0xea, 0x0b, 0x4f, 0xdb, 0xed, 0x28, 0x12, 0x62,
            0x50, 0x78, 0x62, 0x4b, 0xea, 0x8b, 0xeb, 0xf2, 0x4b, 0xde, 0x69, 0x6f, 0xc7, 0x09,
            0x4e, 0x36, 0xa8, 0x0b,
        ]),
        y: BytesN::from_array(env, &[
            0x4f, 0xa1, 0x34, 0xfa, 0x46, 0x74, 0xde, 0x26, 0x0a, 0x34, 0x62, 0xd1, 0x42, 0x3d,
            0x8a, 0x5b, 0xdf, 0x64, 0xbe, 0xde, 0x24, 0xf7, 0xb6, 0x85, 0xa5, 0x5a, 0xb4, 0x91,
            0xcc, 0xbf, 0x02, 0xaa,
        ]),
    }
}

/// Piilo's actual generator H from jubjub.circom: PiiloGeneratorH().
fn circuit_h(env: &Env) -> Point {
    Point {
        x: BytesN::from_array(env, &[
            0x05, 0xd6, 0xef, 0x7a, 0xec, 0xc5, 0x2a, 0x4b, 0xe1, 0x06, 0x06, 0x32, 0x19, 0xec,
            0x13, 0x76, 0x61, 0xd6, 0x81, 0xd1, 0xde, 0xa1, 0x4f, 0x9a, 0x58, 0xf2, 0xd5, 0xb8,
            0x82, 0x53, 0xc9, 0x2d,
        ]),
        y: BytesN::from_array(env, &[
            0x1b, 0x7d, 0x08, 0xb3, 0xea, 0xe0, 0xe0, 0x03, 0xce, 0x5f, 0xf7, 0xf1, 0xea, 0x0b,
            0x09, 0x1c, 0xe2, 0x95, 0x2f, 0x22, 0xc5, 0x45, 0xf2, 0xe3, 0xdf, 0x09, 0x85, 0x2d,
            0x9e, 0xce, 0x49, 0x24,
        ]),
    }
}

/// C_B = commit(500, 111, G, H) — from circuits/input_transfer.json / input_withdraw.json.
fn c_b_point(env: &Env) -> Point {
    Point {
        x: BytesN::from_array(env, &[
            0x2e, 0xfe, 0x42, 0x4f, 0x8e, 0x71, 0x14, 0x64, 0x03, 0xcd, 0x0b, 0xa5, 0x04, 0x6c,
            0x7c, 0x05, 0xa3, 0x0e, 0x6f, 0x76, 0x94, 0xa3, 0x95, 0x82, 0xa6, 0x22, 0xd4, 0xe2,
            0xf7, 0x96, 0xe4, 0xc0,
        ]),
        y: BytesN::from_array(env, &[
            0x5a, 0x11, 0x7e, 0xeb, 0xca, 0xa5, 0x6f, 0x42, 0xe7, 0x46, 0x63, 0x68, 0x6a, 0x25,
            0x86, 0x38, 0xbb, 0x61, 0xa2, 0x39, 0x5f, 0x50, 0xf0, 0x45, 0x51, 0xf6, 0xa2, 0x61,
            0x20, 0xa2, 0x8f, 0x27,
        ]),
    }
}

/// C_A = commit(200, 222, G, H) — from circuits/input_transfer.json.
fn c_a_point(env: &Env) -> Point {
    Point {
        x: BytesN::from_array(env, &[
            0x39, 0x0a, 0xa7, 0x89, 0x99, 0xd5, 0xf9, 0x5f, 0xfe, 0xad, 0x03, 0x67, 0x02, 0xe6,
            0x6e, 0x78, 0xcf, 0x1a, 0x8b, 0xf9, 0x4f, 0xcb, 0x1d, 0x66, 0x20, 0xff, 0xab, 0x37,
            0xc3, 0x81, 0x2d, 0x17,
        ]),
        y: BytesN::from_array(env, &[
            0x20, 0xf7, 0x57, 0xda, 0x72, 0xd2, 0x99, 0xed, 0xe8, 0x70, 0x04, 0x71, 0x9c, 0x8d,
            0xa9, 0x1f, 0x7a, 0x01, 0x42, 0xdc, 0x56, 0x68, 0x6e, 0x38, 0x32, 0xaa, 0x72, 0x48,
            0x17, 0xb4, 0x5d, 0x3a,
        ]),
    }
}

/// C_new = commit(300, 333, G, H) — from circuits/input_transfer.json.
fn c_new_point(env: &Env) -> Point {
    Point {
        x: BytesN::from_array(env, &[
            0x6f, 0x7e, 0xf2, 0x65, 0x1b, 0x23, 0x6e, 0x7c, 0xb8, 0xd5, 0x03, 0x7c, 0x64, 0xdb,
            0x43, 0x22, 0xdb, 0x62, 0x78, 0x98, 0xe7, 0x47, 0xe9, 0x53, 0xd5, 0xea, 0xaa, 0x3b,
            0xd0, 0x29, 0xa4, 0xb7,
        ]),
        y: BytesN::from_array(env, &[
            0x5a, 0xcb, 0x1e, 0x6d, 0x8c, 0xf4, 0x83, 0x02, 0x96, 0xee, 0xc6, 0x9a, 0x56, 0xa2,
            0x0c, 0x9a, 0x60, 0xf4, 0x88, 0xbb, 0x75, 0x52, 0xd9, 0xc5, 0xd4, 0xdf, 0xd3, 0x5c,
            0x51, 0x18, 0x39, 0x14,
        ]),
    }
}

/// VK from circuits/build/transfer_vk.json (generated by snarkjs from transfer_1.zkey).
fn real_transfer_vk(env: &Env) -> VerificationKey {
    let alpha = g1_from_coords_snarkjs(env,
        "2441457570618785688435864919086870713240831727123122768117008811595554267933799727733968313709319899822443474251386",
        "1338581701312941273055642076354490327878183519480806559332437796166035892035419788273656697794810393023571243942572",
    );
    let beta = g2_from_coords_snarkjs(env,
        "1044648454081695623975618500729822851491328068401573847887432385955861187441308573648247725947483410086335448793389",
        "1436268577496976107862941771104813123552366552850131511326895435198325057765207918159733242496679360011680094154836",
        "288996891830114586838655673638655963803717519624954500446802627165599470239655752125896059997133099595671064224414",
        "2493216747289617408280515837657324605582190539674844976852442910678368015983737078677251740300899594528808383144511",
    );
    let gamma = g2_from_coords_snarkjs(env,
        "352701069587466618187139116011060144890029952792775240219908644239793785735715026873347600343865175952761926303160",
        "3059144344244213709971259814753781636986470325476647558659373206291635324768958432433509563104347017837885763365758",
        "1985150602287291935568054521177171638300868978215655730859378665066344726373823718423869104263333984641494340347905",
        "927553665492332455747201965776037880757740193453592970025027978793976877002675564980949289727957565575433344219582",
    );
    let delta = g2_from_coords_snarkjs(env,
        "1369499404959535038367984315478245979873236561508650904180388005922455108384730730751479618404050450513075304221260",
        "1214112031732638642719641635822508739211575074651465564798309311199214945382678055304062981339632557401776983106923",
        "3837198233492527279695144640544379904235653352802352029239492946074213266939642918481900314474859901180316607677079",
        "651708780366451963094864934176048861761775616899827554618508910101332814474079112340481176477477210405707709279568",
    );
    let mut ic = soroban_sdk::Vec::new(env);
    for (x, y) in [
        ("684515562451762932282978858100102108631629232840059837661916472513103916768938781574261852708123310020354878471160",
         "2806983531890179234669454844067236622666401673892076124252773781149841169511707580084028200360986303022025195232203"),
        ("3830326416611293445913687588662444468752172433711607074886870850238268816499866532531778426322991291928992509563993",
         "3829675036621831896473984351973463661621175038623657932525689337913558089210557099742659132286774024416666854451990"),
        ("3005792013953092337999735713294158599990939592757972079527374186017028491793869890206279777731050293514402703914605",
         "2924810082909711116094668275721926740125456294568779095915498061871523163780528486557549871062539851023744851246859"),
        ("1609093808182026999584233719647425325491975927984582033107056270030399698145510435066617033186387562238222376173084",
         "1290032689864890434244447878266940879064429877829724399356249912711922363260632734004735258978277961442493130007057"),
        ("684193540733338452180494915060806141659905111768190212506109815479591352838944098941118859969397788797705682886696",
         "24153786870279110029531500358011366581209099398291663125292460784500405732554008340643641770272786398379105112898"),
        ("2601563921355850077371350241194600953625333177514704511973376658052866030928551986027119561764515534364868775378710",
         "1647099905095846090309177518063603960594601006940554951346105266378705261330686295339748869156950217632460000272795"),
        ("1456396149635273312415806617978614579124250262683154370566591653832926259853749437520151794563776570886275687248756",
         "3265256327881953011311270666656596773338618508054338029406033866236174516940023870663090706730245192522287839027217"),
    ] {
        ic.push_back(g1_from_coords_snarkjs(env, x, y).into());
    }
    VerificationKey { alpha: alpha.into(), beta: beta.into(), gamma: gamma.into(), delta: delta.into(), ic }
}

/// VK from circuits/build/withdraw_vk.json (generated by snarkjs from withdraw_1.zkey).
fn real_withdraw_vk(env: &Env) -> VerificationKey {
    let alpha = g1_from_coords_snarkjs(env,
        "2441457570618785688435864919086870713240831727123122768117008811595554267933799727733968313709319899822443474251386",
        "1338581701312941273055642076354490327878183519480806559332437796166035892035419788273656697794810393023571243942572",
    );
    let beta = g2_from_coords_snarkjs(env,
        "1044648454081695623975618500729822851491328068401573847887432385955861187441308573648247725947483410086335448793389",
        "1436268577496976107862941771104813123552366552850131511326895435198325057765207918159733242496679360011680094154836",
        "288996891830114586838655673638655963803717519624954500446802627165599470239655752125896059997133099595671064224414",
        "2493216747289617408280515837657324605582190539674844976852442910678368015983737078677251740300899594528808383144511",
    );
    let gamma = g2_from_coords_snarkjs(env,
        "352701069587466618187139116011060144890029952792775240219908644239793785735715026873347600343865175952761926303160",
        "3059144344244213709971259814753781636986470325476647558659373206291635324768958432433509563104347017837885763365758",
        "1985150602287291935568054521177171638300868978215655730859378665066344726373823718423869104263333984641494340347905",
        "927553665492332455747201965776037880757740193453592970025027978793976877002675564980949289727957565575433344219582",
    );
    let delta = g2_from_coords_snarkjs(env,
        "1944612790139256496771481459504896451300845823993672938276208070149158800059032892815419363090095161996682695785779",
        "1283749338529803688589932736703527023005201960487844809104524280113950870862993437476789601199418432431607798483365",
        "596380841641675169858115645113805578601906806063818309985912347028970332617976574890681874721623992690164993265457",
        "3416577641056197200092777799102994840636263939546864383924434335878875494757728964734820095332017875423723563680610",
    );
    let mut ic = soroban_sdk::Vec::new(env);
    for (x, y) in [
        ("3212096352413085020712995673465824194260380967530511976024147062413006226890057486972427185500642284935179344854661",
         "581250525416578271545905809540091341406765959462613373225610449183070685430027606943052819623270224926500363434581"),
        ("94665317369659267800493916215115324082897583399345814688596937627634861897903843160402706305100314535519336836238",
         "1531214182561757131869124322152851147384529858959554792480887547922755274019060043211730320260867893594877967153410"),
        ("1153988921737613924619417112966880116343203399872971190311482431306003135164137750369231419276402770271638586361502",
         "3920085612046986203663314570875548428865239912945510973861755759577498903043739157208319422117846305180779935122366"),
        ("1151734189624394528775588824622656214544120423903409386267790867368704573470204879862807152793046218100468827977344",
         "1908955746073359306664651958344839489897837914992868261028914485494297830082107324001371088080632509242896332914927"),
    ] {
        ic.push_back(g1_from_coords_snarkjs(env, x, y).into());
    }
    VerificationKey { alpha: alpha.into(), beta: beta.into(), gamma: gamma.into(), delta: delta.into(), ic }
}

/// Proof from circuits/build/transfer_proof.json — generated by snarkjs from
/// input_transfer.json (B=500, r_B=111, A=200, r_A=222, r_new=333).
fn real_transfer_proof(env: &Env) -> Proof {
    Proof {
        a: g1_from_coords_snarkjs(env,
            "763460020524841353392754504983989091326766131833212325386235433375191335118860068982312564792471767950138233110199",
            "515193310174034260667683982011787438575269523803023142163248226321625868645954271992737527739228454514497914425013",
        ).into(),
        b: g2_from_coords_snarkjs(env,
            "3332650530776251815607499600435630626481629436584020778095222671800224258084424461980253233851525649692565550643944",
            "926390370122140520878469428865128427175894826310139771004050514084770901463744907944718418658444665398705721627008",
            "549159687944695043874735581946195903584519999728558582639573153411575333903204618987381247930183704486985149564781",
            "870824752115241491374144929339511611488236903918790651163746269743889141863074457927770211468684843593944887241303",
        ).into(),
        c: g1_from_coords_snarkjs(env,
            "1142959828256919125604154606374897382528226831016775925936997651449876219923654612320667965216414963163840970256922",
            "2652851832014343148218633669455393639135457354930551546976903759816827050602766671200536462494985534394955512412742",
        ).into(),
    }
}

/// Proof from circuits/build/withdraw_proof.json — generated by snarkjs from
/// input_withdraw.json (r_B=111, C_B=commit(500,111,G,H), B=500).
fn real_withdraw_proof(env: &Env) -> Proof {
    Proof {
        a: g1_from_coords_snarkjs(env,
            "2724024324017475849265269193615307176133567249366992437298134332524512959740571337550750707541335998465480825320169",
            "2724492097546523971893069731209687190835563325981450270573616773541334673869007891060102391206874106385654281971970",
        ).into(),
        b: g2_from_coords_snarkjs(env,
            "871094522177158820580222235953830669417544476293667254597251943064160250648206199725890235452537323452263754921936",
            "798307664342989317787016883165123801951129706168376932026432738803577034321502992437680290158193090091321349015307",
            "1704986215040953610424632628172124644782995318768179117794693111350785009515641314909977983571412048396061597057275",
            "3253608148897554851939646792122830154487117286363600498090920091873862138868904131091742821235983870297171130195119",
        ).into(),
        c: g1_from_coords_snarkjs(env,
            "1155177245937971992601735970912378645561118406337400424694422663353630031920057893197927721736649721002698949068167",
            "1979474480600032634116280670908164822957137369020445799260770137251099442143828124381487006608427880448551227975962",
        ).into(),
    }
}

/// End-to-end golden test: deposit→transfer using the actual compiled Circom
/// circuit. Proves that the real transfer.circom soundness relation (B >= A,
/// no overdraft, commitment openings) integrates correctly with the on-chain
/// Piilo contract logic. If contract and circuit disagree on G, H, or
/// commitment arithmetic, the proof verification fails here.
#[test]
fn real_circom_transfer_proof_is_accepted() {
    let env = Env::default();
    env.cost_estimate().disable_resource_limits();
    env.cost_estimate().budget().reset_unlimited();
    env.mock_all_auths();

    let admin = Address::generate(&env);
    let sac = env.register_stellar_asset_contract_v2(admin.clone());
    let token_id = sac.address();
    let verifier_id = env.register(verifier_contract::WASM, ());

    let mut r = rng();
    let withdraw_vk_placeholder = vk_to_sdk(&env, &setup_circuit::<3>(&mut r).pk.vk);

    let piilo_id = env.register(
        Piilo,
        (circuit_g(&env), circuit_h(&env), verifier_id,
         real_transfer_vk(&env), withdraw_vk_placeholder, token_id.clone()),
    );
    let client = PiiloClient::new(&env, &piilo_id);

    let alice = Address::generate(&env);
    let bob = Address::generate(&env);
    fund(&env, &token_id, &alice, 1_000);

    // deposit(500, r_B=111): contract computes C_B = commit(500, 111, G, H).
    // If this matches c_b_point() from the circuit, the proof below passes.
    client.deposit(&alice, &500, &blinding(&env, 111));

    let deposited_c_b = client.get_account(&alice).unwrap().balance_commitment;
    assert_eq!(deposited_c_b, c_b_point(&env), "contract commit() disagrees with circuit on C_B");

    let c_a = c_a_point(&env);
    let c_new = c_new_point(&env);
    let proof = real_transfer_proof(&env);
    let note = Bytes::from_array(&env, &[0u8; 4]);

    client.transfer(&alice, &bob, &c_a, &c_new, &proof, &note);

    let alice_account = client.get_account(&alice).unwrap();
    assert_eq!(alice_account.balance_commitment, c_new);
    assert_eq!(alice_account.nonce, 1);

    let bob_account = client.get_account(&bob).unwrap();
    assert!(bob_account.has_pending);
    assert_eq!(bob_account.pending_commitment, c_a);
}

/// End-to-end golden test: deposit→withdraw using the actual compiled Circom
/// circuit. Validates that withdraw.circom (proves knowledge of r_B s.t.
/// C_B opens to B) integrates correctly.
#[test]
fn real_circom_withdraw_proof_is_accepted() {
    let env = Env::default();
    env.cost_estimate().disable_resource_limits();
    env.cost_estimate().budget().reset_unlimited();
    env.mock_all_auths();

    let admin = Address::generate(&env);
    let sac = env.register_stellar_asset_contract_v2(admin.clone());
    let token_id = sac.address();
    let verifier_id = env.register(verifier_contract::WASM, ());

    let mut r = rng();
    let transfer_vk_placeholder = vk_to_sdk(&env, &setup_circuit::<6>(&mut r).pk.vk);

    let piilo_id = env.register(
        Piilo,
        (circuit_g(&env), circuit_h(&env), verifier_id,
         transfer_vk_placeholder, real_withdraw_vk(&env), token_id.clone()),
    );
    let client = PiiloClient::new(&env, &piilo_id);
    let token_client = token::Client::new(&env, &token_id);

    let alice = Address::generate(&env);
    fund(&env, &token_id, &alice, 1_000);

    client.deposit(&alice, &500, &blinding(&env, 111));

    let deposited_c_b = client.get_account(&alice).unwrap().balance_commitment;
    assert_eq!(deposited_c_b, c_b_point(&env), "contract commit() disagrees with circuit on C_B");

    let proof = real_withdraw_proof(&env);
    client.withdraw(&alice, &500, &proof);

    assert_eq!(token_client.balance(&alice), 1_000);
    assert_eq!(client.get_vault_balance(), 0);

    let account = client.get_account(&alice).unwrap();
    assert_eq!(account.balance_commitment, commitment::identity(&env));
}
